version: '3'
services:
  nginx:
    build:
      context: ./nginx
      args:
        DOMAIN: localhost
        OTHER_DOMAINS: '127.0.0.1'
        MKCERT_VERSION: v1.4.3
        ENVSUBST_ARGS: '\\$$TARGET_HOST\\$$TARGET_PORT\\$$DOMAIN\\$$RESOLVER'
    environment:
      TARGET_HOST: host.docker.internal
      TARGET_PORT: 3000
      DOMAIN: localhost
      RESOLVER: '127.0.0.11'
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/proxy_config/:/etc/nginx/tmp
    ports:
      - 443:443
      - 80:80
